import type { VisualCultureSource } from "./visualCultureSources";

type SourceRow = readonly [
  id: string,
  label: string,
  sourceUrl: string,
  market: VisualCultureSource["market"],
  region: VisualCultureSource["region"],
  language: VisualCultureSource["language"],
  role: VisualCultureSource["role"],
  collectionMode: VisualCultureSource["collectionMode"],
  priority: VisualCultureSource["priority"],
  topics: VisualCultureSource["topics"],
];

const sourceRows: readonly SourceRow[] = [
  [
    "vogue-runway",
    "Vogue Runway",
    "https://www.vogue.com/fashion-shows",
    "global",
    "europe_america",
    "en",
    "editorial",
    "html_list",
    1,
    ["styling", "outfit"],
  ],
  [
    "photovogue",
    "PhotoVogue",
    "https://www.vogue.com/photovogue",
    "EU",
    "europe_america",
    "en",
    "photography",
    "html_list",
    1,
    ["photography", "creator"],
  ],
  [
    "dazed",
    "Dazed",
    "https://www.dazeddigital.com/latest",
    "EU",
    "europe_america",
    "en",
    "editorial",
    "html_list",
    1,
    ["styling", "fashion_culture", "creator"],
  ],
  [
    "id-magazine",
    "i-D",
    "https://i-d.co/",
    "EU",
    "europe_america",
    "en",
    "editorial",
    "html_list",
    1,
    ["styling", "photography", "fashion_culture"],
  ],
  [
    "another-magazine",
    "AnOther",
    "https://www.anothermag.com/",
    "EU",
    "europe_america",
    "en",
    "editorial",
    "html_list",
    1,
    ["styling", "photography", "magazine"],
  ],
  [
    "the-face",
    "The Face",
    "https://theface.com/",
    "EU",
    "europe_america",
    "en",
    "editorial",
    "html_list",
    2,
    ["fashion_culture", "creator", "photography"],
  ],
  [
    "interview-magazine",
    "Interview",
    "https://www.interviewmagazine.com/",
    "US",
    "europe_america",
    "en",
    "editorial",
    "html_list",
    2,
    ["creator", "photography", "fashion_culture"],
  ],
  [
    "w-magazine",
    "W Magazine",
    "https://www.wmagazine.com/",
    "US",
    "europe_america",
    "en",
    "editorial",
    "html_list",
    2,
    ["styling", "photography", "magazine"],
  ],
  [
    "british-vogue",
    "British Vogue",
    "https://www.vogue.co.uk/fashion",
    "EU",
    "europe_america",
    "en",
    "editorial",
    "html_list",
    1,
    ["styling", "outfit", "photography"],
  ],
  [
    "document-journal",
    "Document Journal",
    "https://www.documentjournal.com/",
    "US",
    "europe_america",
    "en",
    "editorial",
    "html_list",
    2,
    ["photography", "creator", "magazine"],
  ],
  [
    "purple",
    "Purple",
    "https://purple.fr/",
    "EU",
    "europe_america",
    "en",
    "editorial",
    "manual_review",
    3,
    ["photography", "fashion_culture", "magazine"],
  ],
  [
    "032c",
    "032c",
    "https://032c.com/",
    "EU",
    "europe_america",
    "en",
    "editorial",
    "html_list",
    2,
    ["fashion_culture", "styling", "magazine"],
  ],
  [
    "gentlewoman",
    "The Gentlewoman",
    "https://thegentlewoman.co.uk/",
    "EU",
    "europe_america",
    "en",
    "editorial",
    "manual_review",
    3,
    ["styling", "creator", "magazine"],
  ],
  [
    "wallpaper",
    "Wallpaper*",
    "https://www.wallpaper.com/fashion-beauty",
    "EU",
    "europe_america",
    "en",
    "editorial",
    "html_list",
    1,
    ["styling", "exhibition", "fashion_culture"],
  ],
  [
    "nowness",
    "NOWNESS",
    "https://www.nowness.com/",
    "global",
    "europe_america",
    "en",
    "editorial",
    "html_list",
    1,
    ["photography", "fashion_culture", "creator"],
  ],
  [
    "its-nice-that",
    "It's Nice That",
    "https://www.itsnicethat.com/",
    "EU",
    "europe_america",
    "en",
    "editorial",
    "html_list",
    1,
    ["creator", "photography", "fashion_culture"],
  ],
  [
    "aperture",
    "Aperture",
    "https://aperture.org/editorial/",
    "US",
    "europe_america",
    "en",
    "photography",
    "html_list",
    1,
    ["photography", "magazine", "creator"],
  ],
  [
    "bjp-1854",
    "British Journal of Photography",
    "https://www.1854.photography/",
    "EU",
    "europe_america",
    "en",
    "photography",
    "html_list",
    1,
    ["photography", "exhibition", "creator"],
  ],
  [
    "icp",
    "International Center of Photography",
    "https://www.icp.org/",
    "US",
    "europe_america",
    "en",
    "institution",
    "official_page",
    1,
    ["photography", "exhibition"],
  ],
  [
    "met-costume-institute",
    "The Met Costume Institute",
    "https://www.metmuseum.org/about-the-met/collection-areas/the-costume-institute",
    "US",
    "europe_america",
    "en",
    "institution",
    "official_page",
    1,
    ["exhibition", "fashion_culture"],
  ],
  [
    "vam-fashion",
    "V&A Fashion",
    "https://www.vam.ac.uk/collections/fashion",
    "EU",
    "europe_america",
    "en",
    "institution",
    "official_page",
    1,
    ["exhibition", "fashion_culture"],
  ],
  [
    "palais-galliera",
    "Palais Galliera",
    "https://www.palaisgalliera.paris.fr/en",
    "EU",
    "europe_america",
    "en",
    "institution",
    "official_page",
    1,
    ["exhibition", "fashion_culture"],
  ],
  [
    "momu",
    "MoMu Antwerp",
    "https://www.momu.be/en/exhibitions/",
    "EU",
    "europe_america",
    "en",
    "institution",
    "official_page",
    1,
    ["exhibition", "fashion_culture"],
  ],
  [
    "lensculture",
    "LensCulture",
    "https://www.lensculture.com/",
    "global",
    "other_global",
    "en",
    "photography",
    "html_list",
    2,
    ["photography", "creator"],
  ],
  [
    "fashionsnap",
    "FASHIONSNAP",
    "https://www.fashionsnap.com/streetstyle/",
    "JP",
    "japan_korea",
    "ja",
    "editorial",
    "html_list",
    1,
    ["outfit", "styling"],
  ],
  [
    "ginza",
    "GINZA",
    "https://magazineworld.jp/ginza/",
    "JP",
    "japan_korea",
    "ja",
    "editorial",
    "html_list",
    1,
    ["outfit", "styling", "magazine"],
  ],
  [
    "vogue-japan",
    "Vogue Japan",
    "https://www.vogue.co.jp/",
    "JP",
    "japan_korea",
    "ja",
    "editorial",
    "html_list",
    1,
    ["styling", "outfit", "photography"],
  ],
  [
    "vogue-korea",
    "Vogue Korea",
    "https://www.vogue.co.kr/",
    "global",
    "japan_korea",
    "ko",
    "editorial",
    "html_list",
    1,
    ["styling", "photography", "magazine"],
  ],
  [
    "w-korea",
    "W Korea",
    "https://www.wkorea.com/",
    "global",
    "japan_korea",
    "ko",
    "editorial",
    "html_list",
    2,
    ["styling", "photography", "creator"],
  ],
  [
    "tokyo-photo-museum",
    "Tokyo Photographic Art Museum",
    "https://topmuseum.jp/?lang=en",
    "JP",
    "japan_korea",
    "en",
    "institution",
    "official_page",
    1,
    ["photography", "exhibition"],
  ],
  [
    "vogue-singapore",
    "Vogue Singapore",
    "https://vogue.sg/",
    "SG",
    "hk_sg",
    "en",
    "editorial",
    "html_list",
    1,
    ["styling", "photography", "fashion_culture"],
  ],
  [
    "mplus",
    "M+",
    "https://www.mplus.org.hk/en/magazine/",
    "HK",
    "hk_sg",
    "en",
    "institution",
    "official_page",
    1,
    ["exhibition", "fashion_culture", "photography"],
  ],
  [
    "singapore-art-museum",
    "Singapore Art Museum",
    "https://www.singaporeartmuseum.sg/art-events",
    "SG",
    "hk_sg",
    "en",
    "institution",
    "official_page",
    2,
    ["exhibition", "creator", "fashion_culture"],
  ],
  [
    "adobe-news",
    "Adobe Newsroom",
    "https://news.adobe.com/",
    "US",
    "europe_america",
    "en",
    "tool_vendor",
    "official_page",
    1,
    ["tool"],
  ],
  [
    "capture-one",
    "Capture One",
    "https://www.captureone.com/blog",
    "EU",
    "europe_america",
    "en",
    "tool_vendor",
    "official_page",
    1,
    ["tool", "photography"],
  ],
  [
    "blackmagic-resolve",
    "DaVinci Resolve What's New",
    "https://www.blackmagicdesign.com/products/davinciresolve/whatsnew",
    "global",
    "other_global",
    "en",
    "tool_vendor",
    "official_page",
    1,
    ["tool", "photography"],
  ],
  [
    "frame-io",
    "Frame.io Blog",
    "https://frame.io/blog/",
    "US",
    "europe_america",
    "en",
    "tool_vendor",
    "html_list",
    2,
    ["tool", "photography"],
  ],
  [
    "profoto",
    "Profoto Stories",
    "https://www.profoto.com/gb/en/still-photography/profoto-stories/",
    "EU",
    "europe_america",
    "en",
    "tool_vendor",
    "official_page",
    2,
    ["tool", "photography"],
  ],
  [
    "aputure",
    "Aputure Blog",
    "https://aputure.com/en-US/pages/blog",
    "global",
    "other_global",
    "en",
    "tool_vendor",
    "html_list",
    2,
    ["tool", "photography"],
  ],
  [
    "runway",
    "Runway Research",
    "https://runwayml.com/research/",
    "US",
    "europe_america",
    "en",
    "tool_vendor",
    "official_page",
    2,
    ["tool", "creator"],
  ],
  [
    "topaz-labs",
    "Topaz Labs Learn",
    "https://www.topazlabs.com/learn",
    "US",
    "europe_america",
    "en",
    "tool_vendor",
    "html_list",
    2,
    ["tool", "photography"],
  ],
];

export const VISUAL_CULTURE_SOURCES: readonly VisualCultureSource[] =
  Object.freeze(
    sourceRows.map(
      ([
        id,
        label,
        sourceUrl,
        market,
        region,
        language,
        role,
        collectionMode,
        priority,
        topics,
      ]) =>
        Object.freeze({
          collectionMode,
          id,
          label,
          language,
          market,
          priority,
          region,
          role,
          sourceUrl,
          topics: Object.freeze([...topics]),
        })
    )
  );
